- name: Install Redis Repo
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
   # disable_gpg_check: true

- name: Enable redis 6
  ansible.builtin.shell: dnf module enable redis:remi-6.2 -y

- name: Install Redis Server
  ansible.builtin.yum:
    name: redis
    state: installed

- name: Update redis Listen Address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start redis
  ansible.builtin.systemd:
    name: mongodb
    state: restarted
    enabled: yes
  
    