- name: Create parameters
  hosts: localhost
  connection: local
  tasks:
    - name: create or update key value
      community.aws.ssm_parameter:
        name: "{{item.name}}"
        value: "{{item.value}}"
        region: us-east-1
      loop:
        - {name: "dev.cart.REDIS_HOST",value: "redis-dev.ambatis.online"}
        - {name: "dev.cart.CATALOGUE_HOST",value: "catalogue-dev.ambatis.online"}
        - {name: "dev.catalogue.MONGO",value: "true"}
        - {name: "dev.catalogue.MONGO_URL",value: "mongodb://mongodb-dev.ambatis.online:27017/catalogue"}
        - {name: "dev.frontend.CATALOGUE_URL",value: "http://catalogue-dev.ambatis.online:8080/;"}
        - {name: "dev.frontend.CART_URL",value: "http://cart-dev.ambatis.online:8080/;"}
        - {name: "dev.frontend.USER_URL",value: "http://user-dev.ambatis.online:8080/;"}
        - {name: "dev.frontend.PAYMENT_URL",value: "http://payment-dev.ambatis.online:8080/;"}
        - {name: "dev.frontend.SHIPPING_URL",value: "http://shipping-dev.ambatis.online:8080/;"}
        - {name: "dev.payment.CART_HOST",value: "cart-dev.ambatis.online"}
        - {name: "dev.payment.USER_HOST",value: "user-dev.ambatis.online"}
        - {name: "dev.payment.CART_PORT",value: "8080"}
        - {name: "dev.payment.USER_PORT",value: "8080"}
        - {name: "dev.shipping.CART_ENDPOINT",value: "cart-dev.ambatis.online"}
        - {name: "dev.payment.AMQP_HOST",value: "rabbitmq-dev.ambatis.online"}
        - {name: "dev.payment.AMQP_USER",value: "roboshop"}
        - {name: "dev.shipping.DB_HOST",value: "mysql-dev.ambatis.online"}
        - {name: "dev.user.MONGO",value: "true" }
        - {name: "dev.user.MONGO_URL",value: "mongodb://mongodb-dev.ambatis.online:27017/users"}
        - {name: "dev.user.REDDIS_HOST",value: "redis-dev.ambatis.online"}




              ###PASSWORDS ARE FOR LAB PURPOSE ONLY
        - {name: "dev.payment.AMQP_PASS",value: "roboshop123"}

