- name: Install Nginx
  ansible.builtin.yum:
    name: httpd
    state: installed
    
- name: Remove old Http docs
  ansible.builtin.file:
   path: /usr/share/nginx/html/
   state: absent
   

- name: Create http document
  ansible.builtin.file:
   path: /usr/share/nginx/html/
   state: directory
   
- name: Download frontend content
  ansible.builtin.unarchive:
   src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes
  
   